spring.application.name=skins_marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/skins_marketplace
spring.datasource.username=imon
spring.datasource.password=Radmir99204648
spring.jpa.hibernate.sql=true
spring.jpa.hibernate.ddl-auto=update
spring.liquibase=migrations/db.changelog-master.yaml
spring.liquibase.enabled=false

logging.level.ru.itis.skins_marketplace=DEBUG
logging.charset.console=UTF-8

clients.skins-json-url=https://raw.githubusercontent.com/qwkdev/csapi/main/data2.json

storage.path=C:/Project/ORIS_cemectrovki/files

spring.mail.username=radick6752@gmail.com
spring.mail.password=lhinceushufyzfim
spring.mail.port=587
spring.mail.host=smtp.gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.allow8bitmime=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

server.error.whitelabel.enabled=false
server.error.path=/error

