<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Страницы Админа</title>
</head>
<body>
<h1>Работа с пользователем</h1>
<h3>Создать пользователя</h3>
<a href="/admin/users/createUser">Создание пользователя</a>

<h3>Изменить роль пользователя</h3>
<a href="/admin/users/changeRole">User Role</a><br>

<h3>Выдать пользователю скин</h3>
<a href="/admin/users/giveSkins">Выдача User скинов</a><br>
<label>----------------------------------------------</label>

<h3>Создание шаблона скина</h3>
<a href="/admin/skin-templates/create">SkinTemplate</a>
</body>
</html>