<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Спасибо за регистрацию</title>
</head>
<body>
<h1>Подтверждение почты</h1>
<img src="https://tse2.mm.bing.net/th/id/OIP.jMNo9cBj-2n2-X9xB3o5CQHaDt?rs=1&pid=ImgDetMain&o=7&rm=3" alt="">
<h2><a href="http://localhost:8080/confirm/${confirm_code}">Подтвержедние почты</a> </h2>
</body>
</html>